# Generated by Django 2.1 on 2018-11-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('location', models.CharField(blank=True, max_length=250, verbose_name='Location')),
                ('house_type', models.CharField(blank=True, max_length=20, verbose_name='House type')),
                ('rooms_number', models.IntegerField(choices=[(0, 'Studio'), (1, '1'), (2, '2'), (3, '3'), (4, '4')],
                                                     verbose_name='Rooms number')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('floors_number', models.IntegerField(verbose_name='Floor number')),
                ('balcony', models.BooleanField(default=False, verbose_name='Balcony')),
                ('mortgage', models.BooleanField(default=False, verbose_name='Mortgage')),
                ('mortgage_mil', models.BooleanField(default=False, verbose_name='Military mortgage')),
                ('company', models.CharField(max_length=60, verbose_name='Company name')),
            ],
        ),
    ]
